"""
Long-only backtest of the consensus engine.

Walks forward over historical candles: go long when the weighted score is at
or above the entry threshold (and the higher timeframe does not point down),
exit when it is at or below the exit threshold. Signals are filled at the
next candle open and fees are charged on both sides.

The engine uses the SAME code as live — 12 indicator votes, regime-aware
weights (Choppiness Index) and the multi-timeframe filter — so the backtest
measures what the live signal would actually have done. Derivatives
(funding/OI) are live-only snapshots and therefore not part of the
backtest; they shift the score by at most 2 votes.

This is intentionally a simple research baseline, not a production
strategy — pair it with src/validation.py (walk-forward) before believing
any result.
"""
from __future__ import annotations

import numpy as np
import pandas as pd

from . import indicators as ta
from .config import IndicatorSettings, MTF_DEFAULT_BY_TF
from .patterns import pattern_flags
from .signals import (parent_mtf_array, quality_filters, regime_mults,
                      row_votes, score_of)


def warmup_bars(cfg: IndicatorSettings) -> int:
    """Bars needed before the slowest indicator (EMA200) is meaningful."""
    return max(cfg.ema_trend_slow, cfg.bb_period, cfg.adx_period * 2) + 10


def _mtf_enabled(timeframe: str, use_mtf: bool | None) -> bool:
    """Resolve the MTF setting using the signal timeframe, not its parent."""
    if use_mtf is not None:
        return use_mtf
    return MTF_DEFAULT_BY_TF.get(timeframe, True)


def _simulate(df: pd.DataFrame, ind: pd.DataFrame, cfg: IndicatorSettings,
              s: int, e: int, entry_th: float, exit_th: float, fee_pct: float,
              mtf_arr=None, pat_bear: np.ndarray | None = None,
              pattern_lookback: int = 1, slippage_pct: float = 0.0):
    """
    Core loop over bars [s, e).

    Signals are calculated on a closed candle and executed at the next
    candle's open. Position size is determined by the configured risk per
    event and ATR stop distance. A cooldown and daily loss cap prevent a
    cluster of weak signals from repeatedly re-entering the simulation.

    Returns (equity series, trade list, pattern blocks, quality blocks).
    """
    cash = 1.0
    pos = 0
    entry_px = 0.0
    entry_i = -1
    invested = 0.0
    reserve = 0.0
    position_fraction = 0.0
    blocked_patterns = 0
    blocked_quality = 0
    daily_loss_blocks = 0
    trades: list[dict] = []
    equity = pd.Series(1.0, index=df.index[s:e], dtype=float)
    pending: str | None = None
    pending_stop_distance = 0.0
    cooldown_until = s
    day_start_equity = 1.0
    current_day = None
    cost_rate = (float(fee_pct) + float(slippage_pct)) / 100.0

    for i in range(s, e):
        bar_day = df.index[i].date()

        # Execute an order generated by the previous completed candle at this
        # candle's open. A pending entry on the final candle is ignored.
        if pending == "enter" and pos == 0:
            fill = float(df["open"].iloc[i])
            entry_px = fill * (1 + cost_rate)
            stop_pct = (pending_stop_distance / fill) * 100.0 if fill else 0.0
            if stop_pct > 0 and cfg.risk_per_trade_pct > 0:
                position_fraction = min(
                    cfg.max_position_pct / 100.0,
                    cfg.risk_per_trade_pct / stop_pct)
            else:
                position_fraction = cfg.max_position_pct / 100.0
            position_fraction = max(0.0, min(1.0, position_fraction))
            invested = cash * position_fraction
            reserve = cash - invested
            entry_i = i
            pos = 1
        elif pending == "exit" and pos == 1:
            fill = float(df["open"].iloc[i])
            exit_px = fill * (1 - cost_rate)
            trades.append(_trade(df, entry_i, i, entry_px, exit_px,
                                 position_fraction * 100.0))
            cash = reserve + invested * (exit_px / entry_px)
            pos = 0
            invested = reserve = 0.0
            entry_px = 0.0
            entry_i = -1
            position_fraction = 0.0
            cooldown_until = i + max(0, int(cfg.signal_cooldown_bars))
        pending = None

        account_equity = (reserve + invested * (float(df["close"].iloc[i]) / entry_px)
                          if pos == 1 else cash)
        equity.iloc[i - s] = account_equity

        if current_day != bar_day:
            current_day = bar_day
            day_start_equity = account_equity

        daily_loss_hit = (
            cfg.max_daily_loss_pct > 0
            and account_equity <= day_start_equity * (1 - cfg.max_daily_loss_pct / 100.0)
        )
        if daily_loss_hit and pos == 1 and i < e - 1:
            pending = "exit"

        # No order can be filled after the end of the tested window.
        if i >= e - 1:
            continue

        weights, _, _ = regime_mults(ind, i, cfg)
        score = score_of(row_votes(ind, i, cfg), weights)
        quality_ok, _ = quality_filters(ind, i, cfg)
        allow_mtf = mtf_arr is None or mtf_arr[i] >= 0
        pattern_veto = False
        if pat_bear is not None and allow_mtf and quality_ok and score >= entry_th:
            for j in range(max(3, i - pattern_lookback + 1), i + 1):
                if pat_bear[j]:
                    pattern_veto = True
                    break
        if pattern_veto:
            blocked_patterns += 1
        if (not quality_ok and allow_mtf and score >= entry_th):
            blocked_quality += 1
        if daily_loss_hit:
            daily_loss_blocks += 1

        allow_entry = (
            pos == 0
            and score >= entry_th
            and allow_mtf
            and quality_ok
            and not pattern_veto
            and i >= cooldown_until
            and not daily_loss_hit
        )
        if allow_entry:
            pending = "enter"
            atr_value = float(ind["atr"].iloc[i])
            pending_stop_distance = max(0.0, cfg.atr_stop_mult * atr_value)
        elif pos == 1 and (score <= exit_th or daily_loss_hit):
            pending = "exit"

    if pos == 1:  # close any open position at the last available close
        last = float(df["close"].iloc[e - 1])
        exit_px = last * (1 - cost_rate)
        trades.append(_trade(df, entry_i, e - 1, entry_px, exit_px,
                             position_fraction * 100.0))
        cash = reserve + invested * (exit_px / entry_px)
        equity.iloc[-1] = cash

    return equity, trades, blocked_patterns, blocked_quality


def run_backtest(df: pd.DataFrame, cfg: IndicatorSettings | None = None,
                 entry_th: float = 0.25, exit_th: float = -0.25,
                 fee_pct: float = 0.1, parent_df: pd.DataFrame | None = None,
                 parent_timeframe: str = "", use_mtf: bool | None = None,
                 use_patterns: bool = False, timeframe: str = "",
                 slippage_pct: float = 0.05) -> dict:
    """
    Backtest one parameter set. Pass parent_df (higher timeframe, unclosed
    candle dropped) + parent_timeframe to activate the MTF filter.
    use_mtf=None → per-timeframe default (MTF_DEFAULT_BY_TF).
    use_patterns → candlestick-pattern entry veto. Default OFF: the A/B
    walk-forward evidence (README) shows it only helps on some coins
    (BTC 4h) and hurts on others (DOGE 4h) — flip it per coin via the
    dashboard A/B tab if you want it.

    Returns: equity, buy_hold, trades (DataFrame), stats (dict).
    """
    cfg = cfg or IndicatorSettings()
    ind = ta.compute_all(df, cfg)
    warm = warmup_bars(cfg)
    if len(df) <= warm + 10:
        raise ValueError(
            "Not enough candles for a backtest — fetch more (e.g. limit=1000).")

    mtf_on = _mtf_enabled(timeframe, use_mtf)
    mtf_arr = (parent_mtf_array(df, parent_df, parent_timeframe)
               if (mtf_on and parent_timeframe) else None)

    pat_bear = None
    if use_patterns:
        pat_bear = pattern_flags(df)["pat_bear"].to_numpy()

    equity, trades, blocked, quality_blocked = _simulate(
        df, ind, cfg, warm, len(df),
        entry_th, exit_th, fee_pct, mtf_arr, pat_bear, cfg.pattern_lookback,
        slippage_pct)
    buy_hold = df["close"].iloc[warm:].copy()
    buy_hold = buy_hold / buy_hold.iloc[0]

    stats = _stats(equity, buy_hold, pd.DataFrame(trades))
    stats["entries_blocked_by_pattern"] = blocked
    stats["entries_blocked_by_quality"] = quality_blocked
    stats["slippage_pct_per_side"] = slippage_pct
    return {
        "equity": equity,
        "buy_hold": buy_hold,
        "trades": pd.DataFrame(trades),
        "stats": stats,
    }


def _trade(df: pd.DataFrame, entry_i: int, exit_i: int,
           entry_px: float, exit_px: float, position_pct: float = 100.0) -> dict:
    pnl = (exit_px / entry_px - 1.0) * 100.0
    account_pnl = pnl * position_pct / 100.0
    return {
        "entry_time": df.index[entry_i],
        "exit_time": df.index[exit_i],
        "entry": round(entry_px, 4),
        "exit": round(exit_px, 4),
        "pnl_pct": round(pnl, 2),
        "account_pnl_pct": round(account_pnl, 2),
        "position_pct": round(position_pct, 2),
        "bars_held": exit_i - entry_i,
    }


def _stats(equity: pd.Series, buy_hold: pd.Series, t: pd.DataFrame) -> dict:
    total_return = (equity.iloc[-1] - 1.0) * 100.0
    bh = (buy_hold.iloc[-1] - 1.0) * 100.0
    max_dd = (equity / equity.cummax() - 1.0).min() * 100.0

    n = len(t)
    if n:
        account_pnl = t["account_pnl_pct"]
        wins = t[account_pnl > 0]
        losses = t[account_pnl <= 0]
        win_rate = 100.0 * len(wins) / n
        gross_win = wins["account_pnl_pct"].sum()
        gross_loss = abs(losses["account_pnl_pct"].sum())
        profit_factor = float("inf") if gross_loss == 0 else gross_win / gross_loss
        avg_trade = account_pnl.mean()
        loss_streak = max_streak = 0
        for value in account_pnl:
            if value <= 0:
                loss_streak += 1
                max_streak = max(max_streak, loss_streak)
            else:
                loss_streak = 0
    else:
        win_rate, profit_factor, avg_trade, max_streak = 0.0, 0.0, 0.0, 0

    returns = equity.pct_change().dropna()
    if len(returns) > 1 and returns.std(ddof=1) > 0:
        sharpe = float((returns.mean() / returns.std(ddof=1)) * np.sqrt(252))
    else:
        sharpe = 0.0

    return {
        "total_return_pct": total_return,
        "buy_hold_pct": bh,
        "max_drawdown_pct": max_dd,
        "num_trades": n,
        "win_rate_pct": win_rate,
        "profit_factor": profit_factor,
        "avg_trade_pct": avg_trade,
        "expectancy_pct": avg_trade,
        "sharpe": sharpe,
        "max_loss_streak": max_streak,
        "average_position_pct": (float(t["position_pct"].mean()) if n else 0.0),
    }
